# -*- coding: utf-8 -*-
"""issue_4_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r3H-BU3pbVkGMRjGC0PfH5C4RV7kPAFW
"""

from one_hot_encoder import fit_transform
import pytest

#также начнем с чисел и будем рассматривать примеры из прошлых тестов (4примера)
#для примеров в этот раз юзаем one-hot кодирование

def test_wrong_input():
    with pytest.raises(TypeError):
        fit_transform(111)

def test_dota2_spirits():
    spirits = ['Void', 'Ember', 'Storm', 'Earth']
    expected = [('Void', [0, 0, 0, 1]),
                ('Ember', [0, 0, 1, 0]),
                ('Storm', [0, 1, 0, 0]),
                ('Earth', [1, 0, 0, 0])]
    assert fit_transform(spirits) == expected


def test_avito_courses():
    courses = ['python', 'sql', 'stats']
    expected = [('python', [0, 0, 1]),
                ('sql', [0, 1, 0]),
                ('stats', [1, 0, 0])]
    assert fit_transform(courses) == expected


def test_students():
    students = ['Alex', 'Ilya', 'Max', 'Peter']
    expected = [('Alex', [0, 0, 0, 1]),
                ('Ilya', [0, 0, 1, 0]),
                ('Max', [0, 1, 0, 0]),
                ('Peter', [1, 0, 0, 0])]
    assert fit_transform(students) == expected

def test_games():
    games = ['Minecraft', 'Terraria', 'Battlefield', 'Call of Duty']
    expected = [('Minecraft', [0, 0, 0, 1]),
                ('Terraria', [0, 0, 1, 0]),
                ('Battlefield', [0, 1, 0, 0]),
                ('Call of Duty', [1, 0, 0, 0])]
    assert fit_transform(games) == expected